### ISSUE TITLE
initialize the kubernetes master

### ISSUE THREAD

**Issue by sercanacar** [att-comdev/halcyon-vagrant-kubernetes#63]
Hi,

The following fails:

TASK [kube-init : initialize the kubernetes master] ****************************
fatal: [kube1]: FAILED! => {"changed": true, "cmd": "kubeadm init --token ac7da3.b2cofcda6ab01976 --use-kubernetes-version v --api-advertise-addresses 172.16.35.11", "delta": "0:00:02.168654", "end": "2017-02-21 10:47:54.956589", "failed": true, "rc": 1, "start": "2017-02-21 10:47:52.787935", "stderr": "unable to fetch release information. URL: \"https://storage.googleapis.com/kubernetes-release/release/v.txt\" Status: 404 Not Found", "stdout": "[kubeadm] WARNING: kubeadm is in alpha, please do not use it for production clusters.\n[preflight] Running pre-flight checks", "stdout_lines": ["[kubeadm] WARNING: kubeadm is in alpha, please do not use it for production clusters.", "[preflight] Running pre-flight checks"], "warnings": []}
...ignoring

https://storage.googleapis.com/kubernetes-release/release/v.txt
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
</Error>

Or have I configured something incorrectly?

Regards

**Comment by v1k0d3n** [comment]
@sercanacar really sorry for the late response. are you perhaps using this for kolla development? i didn't really know how to respond until someone else expressed the same issues,  and it was realized they didn't run some environment variables ahead of time (which resulted in a kube version of "v" rather than "v1.5.1"). is this issue the same, perhaps?

**Comment by v1k0d3n** [comment]
@sercanacar just checking back before closing the issue. any updates or comments?

**Comment by v1k0d3n** [comment]
no response
